#version: '3.1'
#services:
#  stats-server:
#    ports:
#      - "9090:9090"
#
#  stats-db:
#    image: postgres:14-alpine
#
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats_service_image
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./main-service/
    image: main_service_image
    container_name: main-service
    depends_on:
      - main-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - STAT_SERVER_URL=http://stats-server:9090
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6451:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root